console.log("차트차트 차트업그레이드!!");
console.log("차트차트차트!!")
console.log("차트!!")
console.log("차트!!")
console.log("차트!!")
console.log("차트!!")
console.log("차트!!")
console.log("차트!!")
console.log("차트!!")
console.log("차트!!")
console.log("차트!!")
